### ISSUE TITLE
Edit lines in 3.2

### ISSUE THREAD

**Issue by ashlynnhelm** [ashlynnhelm/team5_project3#3]
Lines to be changed:
- lines 23, 24, and 25: change data to information
- lines 19 & 20, maybe more: look through file and delete any "NOT WORKING" comments
- line 10: add comment at end of line explaining what the imported function does
- line 11: add comment at end of line explaining what the imported function does
- lines 26, 27: change output prints to match the output prints in lines 39 and 40
- line 32: change print to "Would you like to analyze the file now? Type Y/N: "

**Comment by hunterthor** [comment]
Changed lines 26 and 27 to match the output prints in lines 39 and 40. Modified line 32's print text as well.

**Comment by alancavazos** [comment]
Updated lines 23,24,25 , data to information

**Comment by alancavazos** [comment]
Updated comments on line 19 & 20

**Comment by alancavazos** [comment]
Added comments on lines 10 & 11
