### ISSUE TITLE
Project 3 deletion - FINAL STEP/ISSUE, DO LAST

### ISSUE THREAD

**Issue by ashlynnhelm** [ashlynnhelm/team5_project3#4]
Once all other issues have been completed and 3.2 is confirmed to be working, delete project 3 and local_access_http.txt from the repository

**Comment by k3v1nn90** [comment]
3.2 shows to be working on my device.

**Comment by ashlynnhelm** [comment]
Project 3.py and local_access_http.txt files have been deleted
